#!/bin/sh

Xvfb :1 -screen 0 800x600x24 &
export DISPLAY=:1

usermod -aG pulse,pulse-access root
pulseaudio -D --system

./setupTeamspeak &
mopidy &

cd ts3/TeamSpeak3-Client-linux_amd64 

echo TS3 CONNECTION URL
echo $SERVER?nickname=$NAME

LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH" ./ts3client_linux_amd64 $SERVER?nickname=$NAME
