#!/bin/bash

echo Setup teamspeak

function wait-win {
	>&2 echo Waiting for window $1
    while :; do
        for winid in $(xdotool search --name .\*); do
            if [ "$(xdotool getwindowname $winid)" = "$1" ] ; then
                echo "$winid"
				>&2 echo Found window $1
                break 2
            fi
        done
        sleep .2
    done
}

function key {
    # window key
    xdotool key --window $1 $2
    sleep .2
}

function key-repeat {
    # window key times

    for i in `seq 1 $3`; do
        key $1 $2
    done
}

function click {
    # window x y
    xdotool mousemove -w $1 $2 $3
    xdotool click -w $1 1
}

export DISPLAY=:1

## ACCEPT THE LICENSE AGREEMENT
export LICENSE_WINDOW=$(wait-win "License agreement")
key-repeat $LICENSE_WINDOW Next 30      # scroll down the license agreement
key-repeat $LICENSE_WINDOW Tab 2        # tab to the agree button
key $LICENSE_WINDOW Return              # press the accept button

## CLICK CONTINUE IN THE MY TEAMSPEAK WINDOW
export MY_TS_AD_WINDOW=$(wait-win "myTeamSpeak")
sleep 2
key-repeat $MY_TS_AD_WINDOW Tab 3        # tab to the agree button
key $MY_TS_AD_WINDOW Return              # press the accept button

## CLICK CONTINUE WITHOUT LOGGIGN IN
export MY_TS_WINDOW=$(wait-win "myTeamSpeak Account")
sleep 1
key-repeat $MY_TS_WINDOW Tab 4        # tab to the agree button
key $MY_TS_WINDOW Return              # press the accept button

## CONFIGURE CONTINIOUS TRANSMISSION
export MAIN_WINDOW=$(wait-win "TeamSpeak 3")
sleep 1
click $MAIN_WINDOW 350 5                # click the tools drop down
key $MAIN_WINDOW o                      # and open options

export OPTIONS_WINDOW=$(wait-win "Options")
sleep 1
click $OPTIONS_WINDOW 20 20				# focus the	application tab
key-repeat $OPTIONS_WINDOW Down 2       # go down to the playback tab
key-repeat $OPTIONS_WINDOW Tab 13       # tab to voice volume adjustment
key $OPTIONS_WINDOW Home                # drag it down to min
key $OPTIONS_WINDOW Tab                 # tab to sound pack vol
key $OPTIONS_WINDOW Home                # drag it down to min
key-repeat $OPTIONS_WINDOW Tab 4        # tab to apply button
key $OPTIONS_WINDOW Return              # hit apply
click $OPTIONS_WINDOW 20 20				# focus the	application tab
key $OPTIONS_WINDOW Down 3              # go to the capture tab
key-repeat $OPTIONS_WINDOW Tab 8        # tab to push-to-talk
key $OPTIONS_WINDOW Down                # go to continious transmission
key $OPTIONS_WINDOW space               # check the box
key-repeat $OPTIONS_WINDOW Tab 3        # tab to advanced options
key $OPTIONS_WINDOW space               # tick the box
key-repeat $OPTIONS_WINDOW Tab 2        # remove background noise
key $OPTIONS_WINDOW space               # untick the box
key $OPTIONS_WINDOW Tab                 # automatic voice gain control
key $OPTIONS_WINDOW space               # untick the box
key $OPTIONS_WINDOW Return              # close the dialog

firefox $WEBSITE
