#!/bin/bash

function wait-win {
    while :; do
        for winid in $(xdotool search --name .\*); do
            if [ "$(xdotool getwindowname $winid)" = "$1" ] ; then
                echo "$winid"
                break 2
            fi
        done
        sleep .2
    done
}

function key {
    # window key
    xdotool key --window $1 $2
}

function key-repeat {
    # window key times

    for i in `seq 1 $3`; do
        key $1 $2
    done
}

export DISPLAY=:1


## ACCEPT THE LICENSE AGREEMENT
export LICENSE_WINDOW=$(wait-win "License agreement")
key-repeat $LICENSE_WINDOW Next 10      # scroll down the license agreement
key-repeat $LICENSE_WINDOW Tab 5        # tab to the agree button
key $LICENSE_WINDOW Return              # press the accept button

# CANCEL THE SETUP WIZARD
export SETUP_WINDOW=$(wait-win "TeamSpeak 3 Setup Wizard")
key $SETUP_WINDOW Tab                   # tab to the cancel button
key $SETUP_WINDOW Return                # press it
export CONFIRM_WINDOW=$(xdotool search .\* | tail -1)
key $CONFIRM_WINDOW Return              # press enter to confirm

iceweasel $WEBSITE
